name: Update XML on HTML Changes

on:
  push:
    paths:
      - 'events/*.html'
      - 'vinyls/*.html'

jobs:
  update-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Detect new or modified HTML files
        id: detect_html
        run: |
          # Check for both added (A) and modified (M) files
          git diff --name-only --diff-filter=AM HEAD^ HEAD | grep -E '^events/.*\.html$|^vinyls/.*\.html$' > new_files.txt
          if [ -s new_files.txt ]; then
            echo "new_files=true" >> $GITHUB_ENV
          else
            echo "new_files=false" >> $GITHUB_ENV
          fi

      - name: Update XML file
        if: env.new_files == 'true'
        run: |
          # Replace 'path/to/yourfile.xml' with the actual path to your XML file.
          XML_FILE="path/to/yourfile.xml"
          
          while IFS= read -r file; do
            # Extract the title from the HTML file.
            title=$(grep -oP '(?<=<title>)(.*)(?=</title>)' "$file")
            echo "Processing file: $file with title: $title"
            
            # Check if an event with the same title already exists.
            exists=$(xmlstarlet sel -t -v "count(/root/event[title='$title'])" "$XML_FILE")
            if [ "$exists" -eq 0 ]; then
              echo "No duplicate found. Adding new event for '$title'."
              # Append a new event entry with the title.
              xmlstarlet ed --inplace \
                -s "/root" -t elem -n "event" -v "" \
                -s "/root/event[last()]" -t elem -n "title" -v "$title" \
                "$XML_FILE"
            else
              echo "Event with title '$title' already exists, skipping..."
            fi
          done < new_files.txt

      - name: Commit and push changes
        if: env.new_files == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add "$XML_FILE"
          git commit -m 'Update XML with new event/vinyl entries'
          git push
