name: Update XML on HTML Changes

on:
  push:
    paths:
      - 'events/*.html'
      - 'vinyls/*.html'

jobs:
  update-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Detect new or modified HTML files
        id: detect_html
        run: |
          # Check for both added (A) and modified (M) files.
          # Append "|| true" to avoid non-zero exit code when grep finds no matches.
          git diff --name-only --diff-filter=AM HEAD^ HEAD | grep -E '^events/.*\.html$|^vinyls/.*\.html$' > new_files.txt || true
          if [ -s new_files.txt ]; then
            echo "new_files=true" >> $GITHUB_ENV
          else
            echo "new_files=false" >> $GITHUB_ENV
          fi

      - name: Update sitemap.xml
        if: env.new_files == 'true'
        run: |
          # Define the sitemap file and base URL.
          XML_FILE="sitemap.xml"
          BASE_URL="https://eightlimbentertainment.com"
          
          while IFS= read -r file; do
            # Remove the .html extension and construct the full URL.
            url="${file%.html}"
            url="$BASE_URL/$url"
            echo "Processing file: $file with URL: $url"
            
            # Check if this URL already exists in sitemap.xml.
            exists=$(xmlstarlet sel -t -v "count(/urlset/url[loc='$url'])" "$XML_FILE")
            if [ "$exists" -eq 0 ]; then
              echo "No duplicate found. Adding new URL for '$url'."
              # Append a new <url> element with the <loc> set to the URL.
              xmlstarlet ed --inplace \
                -s "/urlset" -t elem -n "url" -v "" \
                -s "/urlset/url[last()]" -t elem -n "loc" -v "$url" \
                "$XML_FILE"
            else
              echo "URL '$url' already exists in sitemap, skipping..."
            fi
          done < new_files.txt

      - name: Commit and push changes
        if: env.new_files == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add sitemap.xml
          git commit -m 'Update sitemap.xml with new event/vinyl entries'
          git push
